/* Generated by tools/generate-faba-catalog.py. */
#define FABA_CATALOG_RECORD_SIZE 160
#define FABA_CATALOG_GROUP_COUNT 7
static const struct { const char *name; unsigned short count; } faba_groups[] = {
    {"Español", 48},
    {"Català", 4},
    {"Français", 69},
    {"Italiano", 129},
    {"Italiano / English", 1},
    {"Español (Latam)", 3},
    {"Neutral", 3},
};
