#!/usr/bin/env python3
"""Generate a pinned, offline catalog. No network access or third-party dependencies."""
import collections, hashlib, json, re, struct
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
GROUPS = [('Spanish','Español'), ('Catalan','Català'), ('French','Français'), ('Italian','Italiano'), ('Italian/English','Italiano / English'), ('Latam','Español (Latam)'), ('Neutral','Neutral')]
RECORD_SIZE = 160

def parse(text):
    entries = []
    for line in text.splitlines():
        cells = [x.strip() for x in line.split('|')]
        if len(cells) == 6 and re.fullmatch(r'\d{4}', cells[1]):
            _, ident, language, title, sku, _ = cells
            if language not in dict(GROUPS) or not title or len(title.encode()) > RECORD_SIZE - 3:
                raise ValueError(f'Invalid catalog row: {line}')
            entries.append(dict(id=ident, language=language, title=title, sku=sku))
    if not entries or len({e['id'] for e in entries}) != len(entries):
        raise ValueError('Empty catalog or duplicate IDs')
    return entries

def main():
    entries = parse((ROOT/'catalog/TAGS.md').read_text())
    out = ROOT/'out/faba-catalog'; out.mkdir(parents=True, exist_ok=True)
    manifest = dict(source=json.loads((ROOT/'catalog/source.json').read_text()), entries=len(entries), record_size=RECORD_SIZE, files=[])
    header = ['/* Generated by tools/generate-faba-catalog.py. */', '#define FABA_CATALOG_RECORD_SIZE 160', '#define FABA_CATALOG_GROUP_COUNT 7', 'static const struct { const char *name; unsigned short count; } faba_groups[] = {']
    for index, (language, label) in enumerate(GROUPS):
        rows = sorted((e for e in entries if e['language']==language), key=lambda e:e['id'])
        data = b'FABACAT1' + struct.pack('<HHI', index, len(rows), RECORD_SIZE)
        for entry in rows:
            data += struct.pack('<H',int(entry['id'])) + entry['title'].encode().ljust(RECORD_SIZE-2,b'\0')
        path = out/f'cat{index}.bin'; path.write_bytes(data)
        manifest['files'].append(dict(file=path.name, device_path=f'E:/faba/{path.name}', language=language, count=len(rows), bytes=len(data), sha256=hashlib.sha256(data).hexdigest()))
        header.append(f'    {{"{label}", {len(rows)}}},')
    header.append('};\n')
    (ROOT/'firmware/pixl-faba/fw/application/src/mod/faba_catalog_data.h').write_text('\n'.join(header))
    (out/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
    (ROOT/'catalog/entries.json').write_text(json.dumps(entries,ensure_ascii=False,indent=2)+'\n')
    print(json.dumps({f['language']: f['count'] for f in manifest['files']})); print('Total:',len(entries))
if __name__ == '__main__': main()
